### ISSUE TITLE
client: connection with server is established twice

### ISSUE THREAD

**Issue by JS1299** [ligomoku/gomoku#237]
### Description:
While implementing online users count feature I noticed that client creates a connection with server twice, and they both keep alive. It appears in strict mode, in case of re-connection the old one should be closed.

### Steps to reproduce:
- Run `yarn dev`,
- Open main page,
- `OnConnectedAsync` backend method called twice with different connection Ids

**Comment by vkuprin** [comment]
Good catch, I hope it's not caused by our last big refactoring @Alequez97

**Comment by Alequez97** [comment]
@vkuprin, Partially because of this. When I touched useSignalR hook I changed logic, that it can accept hubURL parameter and switch connection url between render, but old connection was not properly utilized. I fixed this issue in my last PR - https://github.com/ligomoku/gomoku/pull/236. I hope, @JS1299 will test, and confirm, that one more connection is not opened anymore

**Comment by JS1299** [comment]
Seems that it's fixed now. I'm closing the issue.
